version: '3'
services:
  api:
    container_name: daily-scrum-api
    tty: true
    stdin_open: true
    command: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    depends_on:
      - db
  db:
    image: mysql:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3333:3306
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
volumes:
  mysql-data:
