openapi: 3.0.1
info:
  title: API interface
  description: デイリースクラムアプリ用APIです。
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8000/
paths:
  /users/login:
    post:
      tags:
      - users
      summary: Login
      description: ログイン
      operationId: loginUser
      requestBody:
        description: ログイン
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@hoge.co.jp
                encrypted_password:
                  type: string
                  example: xxx
              required:
                - email
                - encrypted_password
      responses:
        200:
          description: 成功なレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        400:
          description: 無効なユーザーID
          content: {}
        401:
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: object
                    items:
                      example: メールまたはパスワードが間違っています
        404:
          description: ユーザーを見つけていません
          content: {}
        500:
          description: サーバーエラー
          content: {}
  /users/logout:
    post:
      tags:
      - users
      summary: Logout
      description: ログアウト
      operationId: logoutUser
      requestBody:
        description: ログアウト
        required: true
        content: {}
      responses:
        200:
          description: 成功なレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        400:
          description: 無効なユーザーID
          content: {}
        404:
          description: ユーザーを見つけていません
          content: {}
        500:
          description: サーバーエラー
          content: {}
  /users:
    get:
      tags:
      - users
      summary: Get member list
      description: メンバー一覧表示
      operationId: GetUsers
      responses:
        200:
          description: 成功なレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/Users"
        400:
          description: 無効なユーザーID
          content: {}
        404:
          description: ユーザーを見つけていません
          content: {}
        500:
          description: サーバーエラー
          content: {}
  /tasks:
    get:
      tags:
      - tasks
      summary: Get tasks
      description: 複数の日程表示
      operationId: getTasks
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        target_date:
                          type: integer
                          example: 2020.09.23
        400:
          description: Bad request
          content: {}
        404:
          description: Not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
    post:
      tags:
      - tasks
      summary: Add new tasks
      description: 新規登録
      operationId: addNewTasks
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: object
                  properties:
                    target_date:
                        type: integer
                        example: 2020.09.23
                    project_id:
                       type: integer
                       example: 1
                    content:
                       type: string
                       example: 今日の日程はこれです
                  required:
                    - target_date
                    - project_id
                    - content
        required: true
      responses:
        200:
          description: Success
          content: {}
        400:
          description: Bad request
          content: {}
        404:
          description: Not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: id
  /tasks/{id}:
    get:
      tags:
      - tasks
      summary: Get tasks details
      description: 詳細表示
      operationId: getTasksDetails
      parameters:
      - name: id
        in: path
        description: 表示したいタスクid
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tasks"
        400:
          description: Bad request
          content: {}
        404:
          description: Not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
    put:
      tags:
      - tasks
      summary: Edit tasks
      description: 編集
      operationId: editTasks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                    type: integer
                    example: 1
                target_date:
                    type: integer
                    example: 2020.09.23
                project_id:
                   type: integer
                   example: 1
                content:
                   type: string
                   example: 今日の日程はこれです
        required: true
      responses:
        200:
          description: Success
          content: {}
        400:
          description: Bad request
          content: {}
        404:
          description: Not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
      - tasks
      summary: Delete tasks
      description: 削除
      operationId: deleteTasks
      parameters:
      - name: id
        in: path
        description: 削除したいタスクid
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success
          content: {}
        400:
          description: Bad request
          content: {}
        404:
          description: Not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /projects:
    get:
      tags:
      - projects
      summary: Get project by name
      description: nameでプロジェクト名の取得
      operationId: getProjectByName
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      $ref: "#/components/schemas/Projects"
        400:
          description: Bad request
          content: {}
        404:
          description: Not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
components:
  schemas:
    Users:
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: example@hoge.co.jp
        user_name:
              type: string
              example: member1
              description: 対象者名
    Tasks:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: 今日の日程はこれです
          description: 日程内容
        target_date:
          type: integer
          example: 2020.09.23
          description: 対象日
        user:
          type: object
          properties:
            id:
              type: integer
              example: 1
            user_name:
              type: string
              example: member1
              description: 対象者名
        project:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: project1
              description: プロジェクト名
    Projects:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: project1
