default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: 'password'
  ports:
    - 3333:3306

development:
  <<: *default
  database: daily_scrum_development

test:
  <<: *default
  database: daily_scrum_test
